# Docs: https://github.com/Azure/webapps-deploy

name: Build and deploy React app to Azure Web App - bankinstafullserve

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install and build React app
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Upload production build
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: ./frontend/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: ./build

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0406535BF22C466FB68360EF9BC1E533 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A34EE3B0BCD64DE68F0F3355EA05E967 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C63C208F07084B4B9EDF94D3A66C7F85 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'bankinstafullserve'
          slot-name: 'Production'
          package: ./build
